[dataset]
num_samples = 1000
output_dir = "/data/151-1/datasets/synth_test_datasets/cap_pretrain"
num_images = 1
num_turns = 1
interleaved = false

[image]
resolution_type = "fixed"
width = 224
height = 224
